## Como podemos tratar, juntar e armazenar os dados?

Para mexer com os dados, podemos utilizar o Python para buscar, organizar e manipular os dados. O Python é uma ferramenta aberta com diversas aplicações abertas e gratuitas, que permite buscar dados não organizados na internet, lidar com base de dados grandes (acima de 1GB), manipular diversas fontes de dados e fazer modelos de Machine Learning e Inteligencia Artificial.

Atualmente há diversos livros com aplicações em Python para várias finalidades que ensina passo a passo como fazer modelos aplicados.
Nesse workshop vamos passar a base para mexer com dados de forma fácil.

### Como abrir arquivos de dados?

Geralmente optamos por salvar nossos dados quantitativos (e alguns qualitativos) em planilhas ou arquivos de texto (csv). Esses arquivos possuem duas dimensões, ou seja possuem apenas linhas e colunas. 

Quando temos necessidade de olhar os mesmos indivíduos ao longo do tempo (dados longitudinais) adicionamos uma coluna que indica a data de referencia daquela informação, assim é como se tivessemos um cubo de dados, onde a terceira dimensão passa a ser o tempo.

Quando os dados são todos no mesmo instante ou a diferença temporal não importa para o que precisamos, chamamos de dados transversais e nele basicamente mantemos somente as duas dimensões originais.

Mas como vamos abrir os dados no Python?

In [ ]:
import pandas as pd
df = pd.read_excel('dados_abertos_cade.xlsx')
df.head()

,Column1,Column2,Column3,Column4,Column5,Column6,Column7,Column8,Column9,Column10,...,Column26,Column27,Column28,Column29,Column30,Column31,Column32,Column33,Column34,Column35
0,Protocolo,Regime de Notificação,Conversão Rito,Rito,Tipo de julgamento,Natureza da Operação,Cláusula de Não Concorrência,Abrangência da operação,Determinação da Emenda,Pedido de Autorização Precária,...,Data da Decisão SG,Causa do Não Conhecimento pela SG,Causa do Não Conhecimento pelo Tribunal,Tipo Impugnação Tribunal,Hipotese de Procedimento Sumário,Grupo Econômico,Razão Social,Nome Fantasia,Forma Legal,Nacionalidade
1,08700.012662/2015-31,Lei 12.529/2011,-,Sumário,AC Julgado pela SG,Joint-venture clássica,Sim,Nacional,Não,Não,...,26/01/2016,-,-,-,Outros casos,Grupo Eurofarma,Orygen Biotecnologia S.A.,-,S.A. de capital fechado,Brasil
2,08700.012662/2015-31,Lei 12.529/2011,-,Sumário,AC Julgado pela SG,Joint-venture clássica,Sim,Nacional,Não,Não,...,26/01/2016,-,-,-,Outros casos,Pfizer,Pfizer Inc,-,S.A. de capital aberto,Estados Unidos da América
3,08700.012655/2015-30,Lei 12.529/2011,-,Sumário,AC Julgado pela SG,Aquisição de controle,Não,Nacional,Não,Não,...,15/01/2016,-,-,-,Outros casos,Grupo Gávea,Nova Gávea Participações Ltda.,Nova,Ltda,Brasil
4,08700.012655/2015-30,Lei 12.529/2011,-,Sumário,AC Julgado pela SG,Aquisição de controle,Não,Nacional,Não,Não,...,15/01/2016,-,-,-,Outros casos,Grupo JPM,HCM Participações Brasil Ltda.,HCM,Ltda,Brasil

In [ ]:
import pandas as pd
df = pd.read_csv('cade_clinicas_2.csv')
df.head()

C:\Users\henri\AppData\Local\Temp\ipykernel_23020\3110980802.py:1: DtypeWarning: Columns (23,57) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('cade_clinicas_2.csv')

,id,id_unique,numero_sei,ano_documento,assinaturas,descricao_tipo_acesso,descricao_tipo_documento,descricao_tipo_processo,numero_processo,id_unidade,...,corpo_texto,selecionado,qtd_acesso,corpo_texto_formatado,decisao_tribunal,soundex,clicks,descricao_titulo_documento,vltfidf,conteudo
0,abbdc450-7ff1-4990-9bcc-8ae4386592f0,jurisprudencia__1390607,1390607,2024,['Outras'],PUBLICO,Voto Processo Administrativo,Processo Administrativo,08700.004558/2019-05,110000967.0,...,NaN,0,0,NaN,[''],[''],0,NaN,0,SEI/CADE - 1390607 - Voto Processo Administrat...
1,6b5bb7a0-9ad6-438f-96af-8eb3165fabaa,jurisprudencia__1389600,1389600,2024,['Outras'],PUBLICO,Nota Técnica SG,Processo Administrativo,08700.004914/2021-05,110000983.0,...,Processo Administrativo n&ordm;&nbsp;08700.004...,0,0,Processo Administrativo nº 08700.004914/2021-0...,[''],[''],0,NaN,0,SEI/CADE - 1389600 - Nota Técnica\n\n\nNota Té...
2,8a2483e2-0296-431e-85b2-11267caf35ec,jurisprudencia__1389754,1389754,2024,['Outras'],PUBLICO,Parecer,Ato de Concentração Sumário,08700.002236/2024-81,110000980.0,...,\r\n\t\r\n\t\t\r\n\t\t\t\r\n\t\t\tPARECER N&or...,0,0,\r\n\t\r\n\t\t\r\n\t\t\t\r\n\t\t\tPARECER Nº\r...,[''],[''],0,NaN,0,SEI/CADE - 1389754 - Parecer\n\n\n\r\n\t\r\n\t...
3,ba09f364-3ee5-4e28-bba3-c422d53b4ae2,jurisprudencia__1389765,1389765,2024,['Outras'],PUBLICO,Parecer,Ato de Concentração Sumário,08700.002736/2024-12,110000980.0,...,\r\n\t\r\n\t\t\r\n\t\t\t\r\n\t\t\tPARECER N&or...,0,0,\r\n\t\r\n\t\t\r\n\t\t\t\r\n\t\t\tPARECER Nº\r...,[''],[''],0,NaN,0,SEI/CADE - 1389765 - Parecer\n\n\n\r\n\t\r\n\t...
4,46dc8fec-b850-414f-babc-8cd0e1595ec5,jurisprudencia__1389787,1389787,2024,['Outras'],PUBLICO,Parecer,Ato de Concentração Sumário,08700.002774/2024-75,110000980.0,...,\r\n\t\r\n\t\t\r\n\t\t\t\r\n\t\t\tPARECER N&or...,0,0,\r\n\t\r\n\t\t\r\n\t\t\t\r\n\t\t\tPARECER Nº\r...,[''],[''],0,NaN,0,SEI/CADE - 1389787 - Parecer\n\n\n\r\n\t\r\n\t...

### Como criar, filtrar e modificar os dados atuais?

Nem sempre a base de dados que recebemos é exatamente o que precisamos, algumas vezes precisamos modificar os dados que temos para adaptar ao que vamos utilizar. Seja criando uma coluna nova apenas com o ano, filtrando os dados que possuem uma característica específica ou indicando a existencia de um conjunto de termos expecíficos em um texto, as ferramentas abaixo vão ser uteis para a construção desse processo.

In [20]:
import pandas as pd

df = pd.read_csv('base_dados/tratamento_dados/votacao_candidato_munzona_2022_BRASIL.csv')
df.columns

Index(['DT_GERACAO', 'HH_GERACAO', 'ANO_ELEICAO', 'CD_TIPO_ELEICAO',
       'NM_TIPO_ELEICAO', 'NR_TURNO', 'CD_ELEICAO', 'DS_ELEICAO', 'DT_ELEICAO',
       'TP_ABRANGENCIA', 'SG_UF', 'SG_UE', 'NM_UE', 'CD_MUNICIPIO',
       'NM_MUNICIPIO', 'NR_ZONA', 'CD_CARGO', 'DS_CARGO', 'SQ_CANDIDATO',
       'NR_CANDIDATO', 'NM_CANDIDATO', 'NM_URNA_CANDIDATO',
       'NM_SOCIAL_CANDIDATO', 'CD_SITUACAO_CANDIDATURA',
       'DS_SITUACAO_CANDIDATURA', 'CD_DETALHE_SITUACAO_CAND',
       'DS_DETALHE_SITUACAO_CAND', 'CD_SITUACAO_JULGAMENTO',
       'DS_SITUACAO_JULGAMENTO', 'CD_SITUACAO_CASSACAO',
       'DS_SITUACAO_CASSACAO', 'CD_SITUACAO_DIPLOMA', 'DS_SITUACAO_DIPLOMA',
       'TP_AGREMIACAO', 'NR_PARTIDO', 'SG_PARTIDO', 'NM_PARTIDO',
       'NR_FEDERACAO', 'NM_FEDERACAO', 'SG_FEDERACAO',
       'DS_COMPOSICAO_FEDERACAO', 'SQ_COLIGACAO', 'NM_COLIGACAO',
       'DS_COMPOSICAO_COLIGACAO', 'ST_VOTO_EM_TRANSITO', 'QT_VOTOS_NOMINAIS',
       'NM_TIPO_DESTINACAO_VOTOS', 'QT_VOTOS_NOMINAIS_VALIDOS',
       'CD_SIT_TOT_TURNO', 'DS_SIT_TOT_TURNO'],
      dtype='object')

Caso o estudo que estamos fazendo seja focado apenas nas votações para cargos estaduais, temos que olhar colunas que ajudam a filtrar os dados e remover as informações que não temos interesse. Isso é muito importante quando estamos lidando com dados muito grandes, pois reduz a quantidade de memória usada no computador, permitindo adicionar outras informações ou dados sem afetar a eficiencia do computador.

In [ ]:
print(df.DS_ELEICAO.unique())
print(df.DS_CARGO.unique())

['ELEIÇÕES GERAIS ESTADUAIS 2022' 'ELEIÇÃO GERAL FEDERAL 2022']
['Deputado Federal' 'Deputado Estadual' 'Senador' 'Governador'
 'Presidente' 'Deputado Distrital']

In [23]:
df = df[df.DS_CARGO == 'Senador']
df.head()

,DT_GERACAO,HH_GERACAO,ANO_ELEICAO,CD_TIPO_ELEICAO,NM_TIPO_ELEICAO,NR_TURNO,CD_ELEICAO,DS_ELEICAO,DT_ELEICAO,TP_ABRANGENCIA,...,DS_COMPOSICAO_FEDERACAO,SQ_COLIGACAO,NM_COLIGACAO,DS_COMPOSICAO_COLIGACAO,ST_VOTO_EM_TRANSITO,QT_VOTOS_NOMINAIS,NM_TIPO_DESTINACAO_VOTOS,QT_VOTOS_NOMINAIS_VALIDOS,CD_SIT_TOT_TURNO,DS_SIT_TOT_TURNO
166,29/11/2024,03:38:19,2022,2,Eleição Ordinária,1,546,ELEIÇÕES GERAIS ESTADUAIS 2022,02/10/2022,E,...,#NULO#,10001681123,COM A FORÇA DO POVO,PSD / PROS / AVANTE / PTB,N,108,Válido,108,4,NÃO ELEITO
167,29/11/2024,03:38:19,2022,2,Eleição Ordinária,1,546,ELEIÇÕES GERAIS ESTADUAIS 2022,02/10/2022,E,...,#NULO#,10001681123,COM A FORÇA DO POVO,PSD / PROS / AVANTE / PTB,N,3027,Válido,3027,4,NÃO ELEITO
381,29/11/2024,03:38:19,2022,2,Eleição Ordinária,1,546,ELEIÇÕES GERAIS ESTADUAIS 2022,02/10/2022,E,...,#NULO#,10001681123,COM A FORÇA DO POVO,PSD / PROS / AVANTE / PTB,N,4147,Válido,4147,4,NÃO ELEITO
382,29/11/2024,03:38:19,2022,2,Eleição Ordinária,1,546,ELEIÇÕES GERAIS ESTADUAIS 2022,02/10/2022,E,...,#NULO#,10001681123,COM A FORÇA DO POVO,PSD / PROS / AVANTE / PTB,N,1138,Válido,1138,4,NÃO ELEITO
383,29/11/2024,03:38:19,2022,2,Eleição Ordinária,1,546,ELEIÇÕES GERAIS ESTADUAIS 2022,02/10/2022,E,...,#NULO#,10001681123,COM A FORÇA DO POVO,PSD / PROS / AVANTE / PTB,N,6214,Válido,6214,4,NÃO ELEITO

In [24]:
for _,row in df.iterrows():
    print(row)
    break

DT_GERACAO                                            29/11/2024
HH_GERACAO                                              03:38:19
ANO_ELEICAO                                                 2022
CD_TIPO_ELEICAO                                                2
NM_TIPO_ELEICAO                                Eleição Ordinária
NR_TURNO                                                       1
CD_ELEICAO                                                   546
DS_ELEICAO                        ELEIÇÕES GERAIS ESTADUAIS 2022
DT_ELEICAO                                            02/10/2022
TP_ABRANGENCIA                                                 E
SG_UF                                                         AC
SG_UE                                                         AC
NM_UE                                                       ACRE
CD_MUNICIPIO                                                1104
NM_MUNICIPIO                                              JORDÃO
NR_ZONA                                                        5
CD_CARGO                                                       5
DS_CARGO                                                 Senador
SQ_CANDIDATO                                         10001601615
NR_CANDIDATO                                                 900
NM_CANDIDATO                         VANDA DENIR MILANI NOGUEIRA
NM_URNA_CANDIDATO                              DRA. VANDA MILANI
NM_SOCIAL_CANDIDATO                                       #NULO#
CD_SITUACAO_CANDIDATURA                                       12
DS_SITUACAO_CANDIDATURA                                     APTO
CD_DETALHE_SITUACAO_CAND                                       2
DS_DETALHE_SITUACAO_CAND                                DEFERIDO
CD_SITUACAO_JULGAMENTO                                        -3
DS_SITUACAO_JULGAMENTO                                       #NE
CD_SITUACAO_CASSACAO                                          -3
DS_SITUACAO_CASSACAO                                         #NE
CD_SITUACAO_DIPLOMA                                           -3
DS_SITUACAO_DIPLOMA                                          #NE
TP_AGREMIACAO                                          COLIGAÇÃO
NR_PARTIDO                                                    90
SG_PARTIDO                                                  PROS
NM_PARTIDO                   Partido Republicano da Ordem Social
NR_FEDERACAO                                                  -1
NM_FEDERACAO                                              #NULO#
SG_FEDERACAO                                              #NULO#
DS_COMPOSICAO_FEDERACAO                                   #NULO#
SQ_COLIGACAO                                         10001681123
NM_COLIGACAO                                 COM A FORÇA DO POVO
DS_COMPOSICAO_COLIGACAO                PSD / PROS / AVANTE / PTB
ST_VOTO_EM_TRANSITO                                            N
QT_VOTOS_NOMINAIS                                            108
NM_TIPO_DESTINACAO_VOTOS                                  Válido
QT_VOTOS_NOMINAIS_VALIDOS                                    108
CD_SIT_TOT_TURNO                                               4
DS_SIT_TOT_TURNO                                      NÃO ELEITO
Name: 166, dtype: object

In [27]:
dummy_eleito = list()

for _,row in df.iterrows():

    if row.DS_SIT_TOT_TURNO  == 'ELEITO':
        dummy_eleito.append(1)
    elif row.DS_SIT_TOT_TURNO == 'NÃO ELEITO':
        dummy_eleito.append(0)
    else:
        dummy_eleito.append(None)

df['dummy_eleito'] = dummy_eleito
df.head()

,DT_GERACAO,HH_GERACAO,ANO_ELEICAO,CD_TIPO_ELEICAO,NM_TIPO_ELEICAO,NR_TURNO,CD_ELEICAO,DS_ELEICAO,DT_ELEICAO,TP_ABRANGENCIA,...,SQ_COLIGACAO,NM_COLIGACAO,DS_COMPOSICAO_COLIGACAO,ST_VOTO_EM_TRANSITO,QT_VOTOS_NOMINAIS,NM_TIPO_DESTINACAO_VOTOS,QT_VOTOS_NOMINAIS_VALIDOS,CD_SIT_TOT_TURNO,DS_SIT_TOT_TURNO,dummy_eleito
166,29/11/2024,03:38:19,2022,2,Eleição Ordinária,1,546,ELEIÇÕES GERAIS ESTADUAIS 2022,02/10/2022,E,...,10001681123,COM A FORÇA DO POVO,PSD / PROS / AVANTE / PTB,N,108,Válido,108,4,NÃO ELEITO,0
167,29/11/2024,03:38:19,2022,2,Eleição Ordinária,1,546,ELEIÇÕES GERAIS ESTADUAIS 2022,02/10/2022,E,...,10001681123,COM A FORÇA DO POVO,PSD / PROS / AVANTE / PTB,N,3027,Válido,3027,4,NÃO ELEITO,0
381,29/11/2024,03:38:19,2022,2,Eleição Ordinária,1,546,ELEIÇÕES GERAIS ESTADUAIS 2022,02/10/2022,E,...,10001681123,COM A FORÇA DO POVO,PSD / PROS / AVANTE / PTB,N,4147,Válido,4147,4,NÃO ELEITO,0
382,29/11/2024,03:38:19,2022,2,Eleição Ordinária,1,546,ELEIÇÕES GERAIS ESTADUAIS 2022,02/10/2022,E,...,10001681123,COM A FORÇA DO POVO,PSD / PROS / AVANTE / PTB,N,1138,Válido,1138,4,NÃO ELEITO,0
383,29/11/2024,03:38:19,2022,2,Eleição Ordinária,1,546,ELEIÇÕES GERAIS ESTADUAIS 2022,02/10/2022,E,...,10001681123,COM A FORÇA DO POVO,PSD / PROS / AVANTE / PTB,N,6214,Válido,6214,4,NÃO ELEITO,0

### Como adicionar dados na base que temos atualmente?

Ok, já vimos como operar uma base de dados, percorrendo linha a linha, criando e filtrando os dados. Mas como podemos juntar duas base de dados em uma só?
Nesse caso, vamos usar uma função que olha uma informação em comum entre as duas base de dados e junta essas informações, seja mantendo todas as informações da base original (left), da base que estamos adicionando (right) ou somente as que estão presente nas duas bases (inner).

Referencias de como juntar base de dados https://pandas.pydata.org/docs/user_guide/merging.html

In [28]:
import pandas as pd
df1 = pd.read_csv('base_dados/tratamento_dados/consulta_cand_2022_BRASIL.csv', sep =';', encoding='latin-1')
df1.head()

,DT_GERACAO,HH_GERACAO,ANO_ELEICAO,CD_TIPO_ELEICAO,NM_TIPO_ELEICAO,NR_TURNO,CD_ELEICAO,DS_ELEICAO,DT_ELEICAO,TP_ABRANGENCIA,...,CD_GRAU_INSTRUCAO,DS_GRAU_INSTRUCAO,CD_ESTADO_CIVIL,DS_ESTADO_CIVIL,CD_COR_RACA,DS_COR_RACA,CD_OCUPACAO,DS_OCUPACAO,CD_SIT_TOT_TURNO,DS_SIT_TOT_TURNO
0,29/11/2024,03:36:22,2022,2,ELEIÇÃO ORDINÁRIA,1,546,Eleições Gerais Estaduais 2022,02/10/2022,ESTADUAL,...,6,ENSINO MÉDIO COMPLETO,1,SOLTEIRO(A),3,PARDA,595,AGENTE DE SERVIÇOS FUNERÁRIOS E EMBALSAMADOR,5,SUPLENTE
1,29/11/2024,03:36:22,2022,2,ELEIÇÃO ORDINÁRIA,1,546,Eleições Gerais Estaduais 2022,02/10/2022,ESTADUAL,...,6,ENSINO MÉDIO COMPLETO,3,CASADO(A),3,PARDA,598,EMPREGADO DOMÉSTICO,5,SUPLENTE
2,29/11/2024,03:36:22,2022,2,ELEIÇÃO ORDINÁRIA,1,546,Eleições Gerais Estaduais 2022,02/10/2022,ESTADUAL,...,5,ENSINO MÉDIO INCOMPLETO,1,SOLTEIRO(A),2,PRETA,598,EMPREGADO DOMÉSTICO,5,SUPLENTE
3,29/11/2024,03:36:22,2022,2,ELEIÇÃO ORDINÁRIA,1,546,Eleições Gerais Estaduais 2022,02/10/2022,ESTADUAL,...,8,SUPERIOR COMPLETO,1,SOLTEIRO(A),2,PRETA,599,GUIA DE TURISMO,5,SUPLENTE
4,29/11/2024,03:36:22,2022,2,ELEIÇÃO ORDINÁRIA,1,546,Eleições Gerais Estaduais 2022,02/10/2022,ESTADUAL,...,2,LÊ E ESCREVE,3,CASADO(A),1,BRANCA,601,AGRICULTOR,4,NÃO ELEITO

In [29]:
df1.columns

Index(['DT_GERACAO', 'HH_GERACAO', 'ANO_ELEICAO', 'CD_TIPO_ELEICAO',
       'NM_TIPO_ELEICAO', 'NR_TURNO', 'CD_ELEICAO', 'DS_ELEICAO', 'DT_ELEICAO',
       'TP_ABRANGENCIA', 'SG_UF', 'SG_UE', 'NM_UE', 'CD_CARGO', 'DS_CARGO',
       'SQ_CANDIDATO', 'NR_CANDIDATO', 'NM_CANDIDATO', 'NM_URNA_CANDIDATO',
       'NM_SOCIAL_CANDIDATO', 'NR_CPF_CANDIDATO', 'DS_EMAIL',
       'CD_SITUACAO_CANDIDATURA', 'DS_SITUACAO_CANDIDATURA', 'TP_AGREMIACAO',
       'NR_PARTIDO', 'SG_PARTIDO', 'NM_PARTIDO', 'NR_FEDERACAO',
       'NM_FEDERACAO', 'SG_FEDERACAO', 'DS_COMPOSICAO_FEDERACAO',
       'SQ_COLIGACAO', 'NM_COLIGACAO', 'DS_COMPOSICAO_COLIGACAO',
       'SG_UF_NASCIMENTO', 'DT_NASCIMENTO', 'NR_TITULO_ELEITORAL_CANDIDATO',
       'CD_GENERO', 'DS_GENERO', 'CD_GRAU_INSTRUCAO', 'DS_GRAU_INSTRUCAO',
       'CD_ESTADO_CIVIL', 'DS_ESTADO_CIVIL', 'CD_COR_RACA', 'DS_COR_RACA',
       'CD_OCUPACAO', 'DS_OCUPACAO', 'CD_SIT_TOT_TURNO', 'DS_SIT_TOT_TURNO'],
      dtype='object')

In [33]:
merge_df = pd.merge(df, df1, on="NM_CANDIDATO", how="left")
merge_df.head()

,DT_GERACAO_x,HH_GERACAO_x,ANO_ELEICAO_x,CD_TIPO_ELEICAO_x,NM_TIPO_ELEICAO_x,NR_TURNO_x,CD_ELEICAO_x,DS_ELEICAO_x,DT_ELEICAO_x,TP_ABRANGENCIA_x,...,CD_GRAU_INSTRUCAO,DS_GRAU_INSTRUCAO,CD_ESTADO_CIVIL,DS_ESTADO_CIVIL,CD_COR_RACA,DS_COR_RACA,CD_OCUPACAO,DS_OCUPACAO,CD_SIT_TOT_TURNO_y,DS_SIT_TOT_TURNO_y
0,29/11/2024,03:38:19,2022,2,Eleição Ordinária,1,546,ELEIÇÕES GERAIS ESTADUAIS 2022,02/10/2022,E,...,8,SUPERIOR COMPLETO,3,CASADO(A),1,BRANCA,999,OUTROS,4,NÃO ELEITO
1,29/11/2024,03:38:19,2022,2,Eleição Ordinária,1,546,ELEIÇÕES GERAIS ESTADUAIS 2022,02/10/2022,E,...,8,SUPERIOR COMPLETO,3,CASADO(A),1,BRANCA,999,OUTROS,4,NÃO ELEITO
2,29/11/2024,03:38:19,2022,2,Eleição Ordinária,1,546,ELEIÇÕES GERAIS ESTADUAIS 2022,02/10/2022,E,...,8,SUPERIOR COMPLETO,3,CASADO(A),1,BRANCA,999,OUTROS,4,NÃO ELEITO
3,29/11/2024,03:38:19,2022,2,Eleição Ordinária,1,546,ELEIÇÕES GERAIS ESTADUAIS 2022,02/10/2022,E,...,8,SUPERIOR COMPLETO,3,CASADO(A),1,BRANCA,999,OUTROS,4,NÃO ELEITO
4,29/11/2024,03:38:19,2022,2,Eleição Ordinária,1,546,ELEIÇÕES GERAIS ESTADUAIS 2022,02/10/2022,E,...,8,SUPERIOR COMPLETO,3,CASADO(A),1,BRANCA,999,OUTROS,4,NÃO ELEITO

### Como criar variáveis a partir dos textos que temos?

Até agora, aprendemos a lidar com transformações simples e dados numéricos. Mas como fazemos quando temos dados de texto?
Para esse tipo de dado, podemos começar usando Expressões Regulares (Regex). Esse é o método mais simples de buscar informações a partir de certos padrões, sem requerer muita 'tecnologia'.

Para testar os padrões que queremos ver, podemos usar o site https://regex101.com/

In [4]:
import pandas as pd

df = pd.read_csv('catedra/cade_clinicas_2.csv')

colunas_sem_dados = [
                    'palavras', 'relator', 'score', 'nucluster', 'sumario',
                    'representante_legal', 'descricao_assunto', 'quorum',
                    'tags', 'entidade', 'numero_acordao', 'interessados',
                    'numero_ata', 'data_publicacao','documentos_citados',
                    'descricao_protocolo', 'dispositivo_conclusao',
                    'representante_mp', 'selecionado', 'qtd_acesso',
                    'soundex', 'clicks', 'descricao_titulo_documento',
                    'vltfidf'
                    ]
df.drop(columns=colunas_sem_dados, inplace=True)
df.dropna(subset='corpo_texto_formatado', inplace=True)
df.columns

C:\Users\henri\AppData\Local\Temp\ipykernel_3576\2925154773.py:3: DtypeWarning: Columns (23,57) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('catedra/cade_clinicas_2.csv')

Index(['id', 'id_unique', 'numero_sei', 'ano_documento', 'assinaturas',
       'descricao_tipo_acesso', 'descricao_tipo_documento',
       'descricao_tipo_processo', 'numero_processo', 'id_unidade',
       'sigla_unidade', 'descricao_unidade', 'data_ordem', 'data_documento',
       'setor_economico', 'setor_economico_classe', 'setor_economico_divisao',
       'setor_economico_grupo', 'setor_economico_secao',
       'setor_economico_sub_classe', 'partes_processos_like',
       'partes_processos', 'decisao_sg', 'dados_processo',
       'ementa_dispositivo', 'ementa_verbetacao', 'id_colecao',
       'link_documento', 'mercado_relevante', 'documentos_relacionados',
       'qtd_acesso_processo', 'descricao_tipo_protocolo',
       'descricao_especificacao', 'data_processo', 'colecao', '_version_',
       'corpo_texto', 'corpo_texto_formatado', 'decisao_tribunal', 'conteudo'],
      dtype='object')

In [14]:
df.setor_economico.unique()

array(["['Fornecimento e Gestão de Recursos Humanos para Terceiros']",
       "['Produção de Tubos de Aço com Costura']",
       "['Fabricação de Amidos e Féculas de Vegetais e de Óleos de Milho']",
       "['Fabricação de Embalagens de Material Plástico# Geração de Energia Elétrica']",
       "['Concessionárias de Rodovias, Pontes, Túneis e Serviços Relacionados']",
       "['Comércio a Varejo e por Atacado de Veículos Automotores']",
       "['Extração de Minério de Ferro']",
       "['Comércio Atacadista de Mercadorias em Geral, com Predominância de Produtos Alimentícios']",
       "['Desenvolvimento e Licenciamento de Programas de Computador Customizáveis']",
       "['Comércio Atacadista de Energia Elétrica# Geração de Energia Elétrica']",
       "['Comércio Varejista de Livros, Jornais, Revistas e Papelaria# Portais, Provedores de Conteúdo e Outros Serviços de Informação na Internet']",
       "['Atividades de Publicidade não Especificadas Anteriormente']",
       "['Extração de Carvão Mineral']",
       "['Atividades Imobiliárias de Imóveis Próprios']",
       "['Planos de Saúde# Atividades de Atendimento Hospitalar']",
       "['Suporte Técnico, Manutenção e Outros Serviços em Tecnologia da Informação']",
       "['Geração de Energia Elétrica']",
       "['Fabricação de Peças e Acessórios para Veículos Ferroviários# Fabricação de Máquinas e Equipamentos de Uso Geral não Especificados Anteriormente']",
       "['']", "['Comércio Atacadista de Energia Elétrica']",
       "['Fabricação de Laminados Planos e Tubulares de Material Plástico']",
       "['Incorporação de Empreendimentos Imobiliários']",
       "['Construção de Edifícios']",
       "['Construção de Redes de Abastecimento de Água, Coleta de Esgoto e Construções Correlatas']",
       "['Moagem de Trigo e Fabricação de Derivados# Fabricação de Açúcar em Bruto# Comércio Atacadista de Animais Vivos, Alimentos para Animais e Matérias-Primas Agrícolas, Exceto Café e Soja# Comércio Atacadista de Cereais e Leguminosas Beneficiados, Farinhas, Amidos e Féculas']",
       "['Extração de Minério de Alumínio# Metalurgia do Alumínio e suas Ligas']",
       "['Produção de Sementes Certificadas']",
       "['Atividades Auxiliares dos Seguros, da Previdência Complementar e dos Planos de Saúde não Especificados Anteriormente']",
       "['Planos de Saúde# Atividades de Atendimento Hospitalar# Serviços Móveis de Atendimento a Urgências']",
       "['Comércio Atacadista de Combustíveis Sólidos, Líquidos e Gasosos, Exceto Gás Natural e Glp']",
       "['Comércio Varejista de Artigos de uso Doméstico Não Especificados Anteriormente# Aluguel de Objetos Pessoais e Domésticos não Especificados Anteriormente']",
       "['Comércio Varejista de Combustíveis para Veículos Automotores']",
       "['Telecomunicações por Fio']",
       "['Incorporação de Empreendimentos Imobiliários# Atividades Imobiliárias de Imóveis Próprios']",
       "['Aluguel de Máquinas e Equipamentos para Construção Sem Operador']",
       "['Comércio Varejista de Mercadorias em Geral, com Predominância de Produtos Alimentícios - Hipermercados e Supermercados']",
       "['Fabricação de Material Elétrico para Instalações em Circuito de Consumo']",
       "['Extração de Petróleo e Gás Natural']",
       "['Programadoras e Atividades Relacionadas à Televisão por Assinatura']",
       "['Atividades de Consultoria em Gestão Empresarial# Comércio Atacadista de Energia Elétrica# Geração de Energia Elétrica']",
       "['Preparação do Leite# Fabricação de Laticínios']",
       "['Atividades de Serviços de Complementação Diagnóstica e Terapêutica']",
       "['Construção de Rodovias e Ferrovias']",
       "['Fabricação de Medicamentos para Uso Humano']",
       "['Fabricação de Produtos de Panificação']",
       "['Comércio Atacadista de Energia Elétrica# Distribuição de Energia Elétrica# Geração de Energia Elétrica']",
       "['Fabricação de Máquinas e Equipamentos para a Agricultura e Pecuária, Exceto para Irrigação']",
       "['Consultoria em Tecnologia da Informação']",
       "['Fabricação de Produtos Derivados do Cacau, de Chocolates e Confeitos']",
       "['Fabricação de Produtos De Carne# Fabricação de Alimentos para Animais# Comércio Atacadista de Animais Vivos, Alimentos para Animais e Matérias-Primas Agrícolas, Exceto Café e Soja# Transporte Rodoviário de Carga# Curtimento e outras Preparações de Couro# Fabricação de Partes para Calçados, de qualquer Material# Fabricação de Artefatos de Couro não Especificados Anteriormente# Abate de Reses, Exceto Suínos# Abate de Suínos, Aves e Outros Pequenos Animais# Comércio Atacadista de Carnes, Produtos da Carne e Pescado# Comércio Atacadista de Cereais e Leguminosas Beneficiados, Farinhas, Amidos e Féculas# Fabricação de Margarina e Outras Gorduras Vegetais e de Óleos Não-Comestíveis de Animais# Recuperação de Materiais Não Especificados Anteriormente# Comércio Atacadista de Defensivos Agrícolas, Adubos, Fertilizantes e Corretivos do Solo# Comércio Varejista de Produtos Alimentícios em Geral ou Especializado em Produtos Alimentícios Não Especificados Anteriormente; Produtos do Fumo# Comércio Atacadista Especializado de Outros Produtos Intermediários Não Especificados Anteriormente# Fabricação de Equipamentos e Aparelhos Elétricos não Especificados Anteriormente# Armazenamento# Atividades Imobiliárias de Imóveis Próprios# Aluguel de Máquinas e Equipamentos não Especificados Anteriormente# Coleta de Resíduos Não-Perigosos# Carga e Descarga# Locação de Meios de Transporte, Exceto Automóveis, sem Condutor# Fabricação de Produtos Diversos não Especificados Anteriormente# Comércio Varejista de Outros Produtos Novos Não Especificados Anteriormente# Comércio Atacadista de Produtos Químicos e Petroquímicos, Exceto Agroquímicos# Cultivo de Cereias# Criação de Bovinos# Atividades de Apoio à Produção Florestal# Atividades de Apoio à Agricultura# Outras Sociedades de Participação, Exceto Holdings# Moagem e Fabricação de Produtos de Origem Vegetal Não Especificados Anteriormente# Fabricação de Calçados de Materiais não Especificados Anteriormente# Produção Florestal - Florestas Plantadas# Confecção de Peças de Vestuário, exceto Roupas Íntimas# Comércio Varejista de Calçados e Artigos de Viagem# Comércio Atacadista de Calçados e Artigos de Viagem# Comércio Varejista de Artigos do Vestuário e Acessórios# Comércio Atacadista de Artigos do Vestuário e Acessórios']",
       "['Comércio Varejista Especializado de Equipamentos de Telefonia e Comunicação']",
       "['Fornecimento e Gestão de Recursos Humanos para Terceiros# Serviços de Catering, Bufê e Outros Serviços de Comida Preparada']",
       "['Fabricação de Malte, Cervejas e Chopes']",
       "['Outras Atividades de Serviços Financeiros Não Especificados Anteriormente']",
       "['Fabricação de Artefatos de Concreto, Cimento, Fibrocimento, Gesso e Materiais Semelhantes']",
       "['Atividades Imobiliárias de Imóveis Próprios# Comércio Atacadista de Mercadorias em Geral, com Predominância de Produtos Alimentícios']",
       "['Educação Infantil - Creche# Educação Infantil - Pré-Escola# Ensino Fundamental# Ensino Médio']",
       "['Transporte Aéreo de Passageiros Regular# Transporte Aéreo de Carga']",
       "['Artes Cênicas, Espetáculos e Atividades Complementares']",
       "['Atividades de Contabilidade, Consultoria e Auditoria Contábil e Tributária']",
       "['Serviços de Engenharia# Atividades de Organizações Associativas Profissionais']",
       "['Comércio Atacadista de Máquinas, Aparelhos e Equipamentos para Uso Agropecuário; Partes e Peças']",
       "['Coleta de Resíduos Perigosos# Tratamento e Disposição de Resíduos Não-Perigosos']",
       "['Produção de Gás; Processamento de Gás Natural; Distribuição Gasosos por Redes Urbanas']",
       "['Transporte Escolar']",
       "['Parques de Diversão e Parques Temáticos']",
       "['Fabricação de Produtos à Base de Café']",
       "['Fabricação de Válvulas, Registros e Dispositivos Semelhantes# Fabricação de Máquinas e Equipamentos para as Indústrias de Celulose, Papel e Papelão e Artefatos']",
       "['Transmissão de Energia Elétrica# Comércio Atacadista de Energia Elétrica# Geração de Energia Elétrica']",
       "['Transportes Aquaviários Não Especificados Anteriormente# Armazenamento']",
       "['Cultivo de Cereias# Atividades de Apoio à Agricultura# Cultivo de Soja']",
       "['Fabricação de Produtos Químicos Orgânicos não Especificados Anteriormente']",
       "['Comércio Atacadista de Produtos Farmacêuticos para Uso Humano e Veterinário']",
       "['Produção de Forjados de Aço e de Metais Não-Ferrosos e Suas Ligas']",
       "['Fabricação de Preparações Farmacêuticas']",
       "['Planos de Saúde# Atividades de Serviços de Complementação Diagnóstica e Terapêutica']",
       "['Comércio Atacadista de Instrumentos e Materiais para Uso Médico, Cirúrgico, Ortopédico e Odontológico']",
       "['Comércio Atacadista de Carnes, Produtos da Carne e Pescado# Abate de Reses, Exceto Suínos']",
       "['Atividades de Apoio à Extração de Petróleo e Gás Natural']",
       "['Produção Florestal - Florestas Plantadas# Atividades de Apoio à Produção Florestal# Fabricação de Celulose e outras Pastas para a Fabricação de Papel']",
       "['Comércio de Peças e Acessórios para Veículos Automotores']",
       "['Serviços Especializados para Construção Não Especificados Anteriormente# Serviços Combinados de Escritório e Apoio Administrativo# Construção de Edifícios# Atividades de Limpeza não Especificadas Anteriormente# Atividades Imobiliárias de Imóveis Próprios# Atividades de Consultoria em Gestão Empresarial# Serviços de Engenharia# Outras Sociedades de Participação, Exceto Holdings# Testes e Análises Técnicas# Atividades de Apoio à Gestão de Saúde# Coleta de Resíduos Não-Perigosos# Obras para Geração e Distribuição de Energia Elétrica e para Telecomunicações']",
       "['Educação Superior - Graduação e Pós-Graduação# Edição de Livros']",
       "['Fabricação de Óleos Vegetais em Bruto, Exceto Óleo de Milho# Fabricação de Biocombustíveis, exceto Álcool# Comércio Atacadista Especializado em Produtos Alimentícios Não Especificados Anteriormente']",
       "['Comércio Atacadista de Equipamentos e Artigos de Uso Pessoal e Doméstico Não Especificados Anteriormente']",
       "['Coleta de Resíduos Perigosos']",
       "['Atividades Auxiliares dos Transportes Aquaviários não Especificadas Anteriormente']",
       "['Coleta de Resíduos Não-Perigosos']",
       "['Atividades de Consultoria em Gestão Empresarial# Atividades de Intermediários em Transações de Títulos, Valores Mobiliários e Mercadorias# Corretores e Agentes de Seguros, de Planos de Previdência Complementar e de Saúde']",
       "['Serviços de Engenharia']",
       "['Fabricação e Produtos Farmoquímicos']",
       "['Transporte Ferroviário de Carga']",
       "['Atividades de Administração de Fundos por Contrato ou Comissão']",
       "['Comércio Varejista de Artigos do Vestuário e Acessórios# Comércio Varejista de Calçados e Artigos de Viagem']",
       "['Fabricação de Motores e Turbinas, Exceto para Aviões e Veículos Rodoviários']",
       "['Comércio Varejista de Artigos de uso Doméstico Não Especificados Anteriormente']",
       "['Comércio Atacadista de Produtos Alimentícios em Geral']",
       "['Desenvolvimento e Licenciamento de Programas de Computador Customizáveis# Desenvolvimento e Licenciamento de Programas de Computador Não-Customizáveis# Portais, Provedores de Conteúdo e Outros Serviços de Informação na Internet']",
       "['Fabricação de Embalagens de Material Plástico']",
       "['Captação, Tratamento e Distribuição de Àgua# Gestão de Redes de Esgoto']",
       "['Bancos Múltiplos, com Carteira Comercial# Administração de Cartões de Crédito# Atividades Auxiliares dos Serviços Financeiros não Especificadas Anteriormente']",
       "['Fundos de Investimento']",
       "['Atividades de Intermediários em Transações de Títulos, Valores Mobiliários e Mercadorias']",
       "['Fabricação de Medicamentos para Uso Veterinário']",
       "['Manutenção e Reparação de Máquinas e Equipamentos da Indústria Mecânica# Montagem de Instalações Industriais e de Estrutura Metálicas']",
       "['Fabricação de Fios, Cabos e Condutores Elétricos Isolados']",
       "['Atividades Auxiliares dos Serviços Financeiros não Especificadas Anteriormente']",
       "['Extração de Minerais para Fabricação de Adubos, Fertilizantes e Outros Produtos Químicos']",
       "['Transporte Marítimo de  Longo Curso']",
       "['Fabricação de Produtos Alimentícios Não Especificados Anteriormente# Curtimento e outras Preparações de Couro']",
       "['Comércio Atacadista de Gás Liqüefeito de Petróleo (Glp)']",
       "['Gestão e Administração da Propriedade Imobiliária# Atividades Imobiliárias de Imóveis Próprios']",
       "['Gestão e Administração da Propriedade Imobiliária# Incorporação de Empreendimentos Imobiliários']",
       "['Atividades de Serviços Prestados Principalmente às Empresas não Especificadas Anteriormente']",
       "['Captação, Tratamento e Distribuição de Àgua']",
       "['Transporte Rodoviário Coletivo de Passageiros, com Itinerário Fixo, Intermunicipal, Interestadual e Internacional# Atividades Profissionais, Científicas e Técnicas não Especificadas Anteriormente# Serviços de Reservas e Outros Serviços de Turismo não Especificados Anteriormente# Portais, Provedores de Conteúdo e Outros Serviços de Informação na Internet# Agências de Viagens']",
       "['Abate de Suínos, Aves e Outros Pequenos Animais# Fabricação de Produtos De Carne# Abate de Reses, Exceto Suínos']",
       "['Atividades de Organizações Associativas Profissionais# Atividades de Intermediários em Transações de Títulos, Valores Mobiliários e Mercadorias']",
       "['Fabricação de Farinha de Milho e Derivados, Exceto Óleos de Milho']",
       "['Planos de Saúde# Atividades de Atenção Ambulatorial Executadas por Médicos e Odontólogos# Atividades de Serviços de Complementação Diagnóstica e Terapêutica']",
       "['Cultivo de Cereias# Cultivo de Algodão Herbáceo e de Outras Fibras de Lavouras Temporária# Cultivo de Soja']",
       "['Atividades Técnicas Relacionadas à Arquitetura e Engenharia# Serviços de Arquitetura']",
       "['Obras de Urbanização - Ruas, Praças e Calçadas']",
       "['Cultivo de Cereias# Fabricação de Farinha de Milho e Derivados, Exceto Óleos de Milho# Transporte Rodoviário de Carga# Armazenamento# Comércio Atacadista de Animais Vivos, Alimentos para Animais e Matérias-Primas Agrícolas, Exceto Café e Soja# Comércio Atacadista de Cereais e Leguminosas Beneficiados, Farinhas, Amidos e Féculas# Comércio Atacadista de Defensivos Agrícolas, Adubos, Fertilizantes e Corretivos do Solo']",
       "['Armazenamento']",
       "['Comércio Atacadista de Produtos Alimentícios em Geral# Comércio Atacadista de Equipamentos e Artigos de Uso Pessoal e Doméstico Não Especificados Anteriormente']",
       "['Comércio Atacadista de Máquinas e Equipamentos para Uso Industrial; Partes e Peças']",
       "['Bancos Múltiplos, com Carteira Comercial# Atividades de Intermediários em Transações de Títulos, Valores Mobiliários e Mercadorias# Fundos de Investimento']",
       "['Fabricação de Intermediários para Fertilizantes']",
       "['Comércio Atacadista de Produtos Químicos e Petroquímicos, Exceto Agroquímicos']",
       "['Cultivo de Cereias# Fabricação de Alimentos para Animais# Armazenamento# Comércio Atacadista de Soja# Comércio Atacadista de Cereais e Leguminosas Beneficiados, Farinhas, Amidos e Féculas# Cultivo de Soja']",
       "['Fabricação de Tintas, Vernizes, Esmaltes e Lacas']",
       "['Instalações Elétricas# Atividades de Monitoramento de Sistemas de Segurança']",
       "['Fabricação de Defensivos Agrícolas']",
       "['Serviços Especializados para Construção Não Especificados Anteriormente']",
       "['Serviços Combinados para Apoio a Edifícios, Exceto Condomínios Prediais']",
       "['Gestão e Administração da Propriedade Imobiliária']",
       "['Fabricação e Produtos Farmoquímicos# Fabricação de Preparações Farmacêuticas']",
       "['Fabricação de Produtos Derivados do Cacau, de Chocolates e Confeitos# Comércio Varejista de Produtos de Padaria, Laticínio, Doces, Balas e Semelhantes# Comércio Varejista de Bebidas# Comércio Atacadista Especializado em Produtos Alimentícios Não Especificados Anteriormente']",
       "['Fabricação de Cosméticos, Produtos de Perfumaria e de Higiene Pessoal# Fabricação de Medicamentos para Uso Humano']",
       "['Produção de Sementes Certificadas# Atividades de Pós-Colheita']",
       "['Transporte Rodoviário de Carga']",
       "['Obras de Engenharia Civil não Especificadas Anteriormente# Obras Portuárias, Marítimas e Fluviais']",
       "['Navegação de Apoio']",
       "['Comércio Varejista de Produtos Alimentícios em Geral ou Especializado em Produtos Alimentícios Não Especificados Anteriormente; Produtos do Fumo']",
       "['Fabricação de Produtos Cerâmicos Refratários']",
       "['Cultivo de Cereias# Comércio Atacadista de Soja# Comércio Atacadista de Cereais e Leguminosas Beneficiados, Farinhas, Amidos e Féculas# Cultivo de Soja']",
       "['Desenvolvimento e Licenciamento de Programas de Computador Customizáveis# Desenvolvimento e Licenciamento de Programas de Computador Não-Customizáveis# Suporte Técnico, Manutenção e Outros Serviços em Tecnologia da Informação# Desenvolvimento de Programas de Computador Sob Encomenda']",
       "['Locação de Automóveis sem Condutor']",
       "['Fabricação de Farinha de Milho e Derivados, Exceto Óleos de Milho# Fabricação de Amidos e Féculas de Vegetais e de Óleos de Milho# Fabricação de Álcool# Geração de Energia Elétrica']",
       "['Fabricação de Aeronaves']",
       "['Obras para Geração e Distribuição de Energia Elétrica e para Telecomunicações']",
       "['Fabricação de Adubos e Fertilizantes']",
       "['Telecomunicações por Fio# Tratamento de Dados, Provedores de Serviços de Aplicação de Hospedagem Internet']",
       "['Atividades de Produção Cinematográfica, de Vídeos e de Programas de Televisão']",
       "['Desenvolvimento e Licenciamento de Programas de Computador Não-Customizáveis# Suporte Técnico, Manutenção e Outros Serviços em Tecnologia da Informação# Comércio Atacadista de Ferragens e Ferramentas# Reparação e manutenção de equipamentos eletroeletrônicos de uso pessoal e doméstico']",
       "['Fabricação de Equipamentos Hidráulicos e Pneumáticos, Exceto Válvulas']",
       "['Desenvolvimento e Licenciamento de Programas de Computador Não-Customizáveis# Fabricação de Máquinas e Equipamentos para a Agricultura e Pecuária, Exceto para Irrigação']",
       "['Restaurantes e Outros Serviços de Alimentação e Bebidas']",
       "['Telecomunicações Sem Fio# Consultoria em Tecnologia da Informação# Suporte Técnico, Manutenção e Outros Serviços em Tecnologia da Informação']",
       "['Comércio a Varejo e por Atacado de Veículos Automotores# Comércio por Atacado, Exceto Veículos Automotores e Motocicletas, Peças e Acessórios']",
       "['Planos de Saúde']", "['Resseguros']",
       "['Administração de Cartões de Crédito']",
       "['Fabricação de Automóveis, Camionetas e Utilitários']",
       "['Comércio Varejista de Artigos Recreativos e Esportivos']",
       "['Cultivo de Cana-de-açúcar']",
       "['Transmissão de Energia Elétrica']",
       "['Atividades Profissionais, Científicas e Técnicas não Especificadas Anteriormente']",
       "['Gestão de Portos e Terminais']",
       "['Curtimento e outras Preparações de Couro']",
       "['Fabricação de Máquinas-Ferramenta']",
       "['Tratamento de Dados, Provedores de Serviços de Aplicação de Hospedagem Internet']",
       "['Fabricação de Geradores, Transformadores e Motores Elétricos']",
       "['Desenvolvimento e Licenciamento de Programas de Computador Não-Customizáveis']",
       "['Hotéis e Similares']",
       "['Educação Profissional de Nível Técnico']",